package settings

type Table struct {
	Name string
	// Map of conditions where 0 = false, 1 = true, 2 = unknown. It is not necessary to map the unknowns.
	ConditionsValues map[string]int
}

func GetTables() []Table {

	table1 := Table{
		Name: "213",
		ConditionsValues: map[string]int{
			"ATM":                      2,
			"CardnNotPresent":          2,
			"CardPresent":              2,
			"VSDC":                     0,
			"NotVSDC":                  2,
			"TandE":                    2,
			"CPS":                      0,
			"AccountVerification":      2,
			"CreditVoucher":            0,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table2 := Table{
		Name: "215",
		ConditionsValues: map[string]int{
			"ATM":                      2,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     0,
			"NotVSDC":                  2,
			"TandE":                    1,
			"CPS":                      1,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table3 := Table{
		Name: "216",
		ConditionsValues: map[string]int{
			"ATM":                      2,
			"CardnNotPresent":          1,
			"CardPresent":              0,
			"VSDC":                     2,
			"NotVSDC":                  2,
			"TandE":                    1,
			"CPS":                      1,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table4 := Table{
		Name: "220",
		ConditionsValues: map[string]int{
			"ATM":                      2,
			"CardnNotPresent":          2,
			"CardPresent":              2,
			"VSDC":                     2,
			"NotVSDC":                  2,
			"TandE":                    2,
			"CPS":                      2,
			"AccountVerification":      1,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table5 := Table{
		Name: "221",
		ConditionsValues: map[string]int{
			"ATM":                      2,
			"CardnNotPresent":          2,
			"CardPresent":              2,
			"VSDC":                     2,
			"NotVSDC":                  2,
			"TandE":                    2,
			"CPS":                      2,
			"AccountVerification":      2,
			"CreditVoucher":            1,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table6 := Table{
		Name: "225",
		ConditionsValues: map[string]int{
			"ATM":                      1,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     2,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      0,
			"CPS":                      0,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  1,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table7 := Table{
		Name: "228",
		ConditionsValues: map[string]int{
			"ATM":                      1,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     2,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      0,
			"CPS":                      1,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  1,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table8 := Table{
		Name: "229",
		ConditionsValues: map[string]int{
			"ATM":                      1,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     2,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      0,
			"CPS":                      2,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      1,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table9 := Table{
		Name: "230",
		ConditionsValues: map[string]int{
			"ATM":                      1,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     2,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      0,
			"CPS":                      2,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           1,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table10 := Table{
		Name: "238",
		ConditionsValues: map[string]int{
			"ATM":                      0,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     2,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      1,
			"CPS":                      2,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  1,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 1,
			"Authorization":            0,
			"Advice":                   0,
		},
	}

	table11 := Table{
		Name: "239",
		ConditionsValues: map[string]int{
			"ATM":                      0,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     2,
			"NotVSDC":                  2,
			"TandE":                    1,
			"POS":                      1,
			"CPS":                      1,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 1,
			"Authorization":            0,
			"Advice":                   0,
		},
	}

	table12 := Table{
		Name: "240",
		ConditionsValues: map[string]int{
			"ATM":                      2,
			"CardnNotPresent":          1,
			"CardPresent":              0,
			"VSDC":                     2,
			"NotVSDC":                  2,
			"TandE":                    1,
			"CPS":                      1,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 1,
			"Authorization":            0,
			"Advice":                   0,
		},
	}

	table13 := Table{
		Name: "244",
		ConditionsValues: map[string]int{
			"ATM":                      0,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     2,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      1,
			"CPS":                      2,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 1,
			"Authorization":            0,
			"Advice":                   2,
		},
	}

	table14 := Table{
		Name: "245",
		ConditionsValues: map[string]int{
			"ATM":                      1,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     2,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      0,
			"CPS":                      2,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 1,
			"Authorization":            0,
			"Advice":                   0,
		},
	}

	table15 := Table{
		Name: "249",
		ConditionsValues: map[string]int{
			"ATM":                      1,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     2,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      0,
			"CPS":                      2,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      1,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 1,
			"Authorization":            0,
			"Advice":                   0,
		},
	}

	table16 := Table{
		Name: "254",
		ConditionsValues: map[string]int{
			"ATM":                      2,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     1,
			"NotVSDC":                  2,
			"TandE":                    2,
			"CPS":                      0,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table17 := Table{
		Name: "255",
		ConditionsValues: map[string]int{
			"ATM":                      2,
			"CardnNotPresent":          2,
			"CardPresent":              2,
			"VSDC":                     1,
			"NotVSDC":                  2,
			"TandE":                    2,
			"CPS":                      2,
			"AccountVerification":      1,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table18 := Table{
		Name: "256",
		ConditionsValues: map[string]int{
			"ATM":                      2,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     1,
			"NotVSDC":                  2,
			"TandE":                    1,
			"CPS":                      1,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table19 := Table{
		Name: "259",
		ConditionsValues: map[string]int{
			"ATM":                      1,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     1,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      0,
			"CPS":                      0,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table20 := Table{
		Name: "260",
		ConditionsValues: map[string]int{
			"ATM":                      1,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     1,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      0,
			"CPS":                      1,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  1,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table21 := Table{
		Name: "261",
		ConditionsValues: map[string]int{
			"ATM":                      1,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     1,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      0,
			"CPS":                      0,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           1,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table22 := Table{
		Name: "262",
		ConditionsValues: map[string]int{
			"ATM":                      2,
			"CardnNotPresent":          2,
			"CardPresent":              2,
			"VSDC":                     1,
			"NotVSDC":                  2,
			"TandE":                    2,
			"CPS":                      2,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         1,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table23 := Table{
		Name: "263",
		ConditionsValues: map[string]int{
			"ATM":                      1,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     1,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      0,
			"CPS":                      2,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      1,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	table24 := Table{
		Name: "264",
		ConditionsValues: map[string]int{
			"ATM":                      1,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     1,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      0,
			"CPS":                      2,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      1,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 1,
			"Authorization":            0,
			"Advice":                   0,
		},
	}

	table25 := Table{
		Name: "265",
		ConditionsValues: map[string]int{
			"ATM":                      2,
			"CardnNotPresent":          2,
			"CardPresent":              2,
			"VSDC":                     1,
			"NotVSDC":                  2,
			"TandE":                    2,
			"CPS":                      2,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            0,
			"Advice":                   1,
		},
	}

	table26 := Table{
		Name: "267",
		ConditionsValues: map[string]int{
			"ATM":                      0,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     1,
			"NotVSDC":                  2,
			"TandE":                    1,
			"POS":                      1,
			"CPS":                      1,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 1,
			"Authorization":            0,
			"Advice":                   0,
		},
	}

	table27 := Table{
		Name: "269",
		ConditionsValues: map[string]int{
			"ATM":                      0,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     1,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      1,
			"CPS":                      2,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 1,
			"Authorization":            0,
			"Advice":                   0,
		},
	}

	table28 := Table{
		Name: "271",
		ConditionsValues: map[string]int{
			"ATM":                      1,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     1,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      0,
			"CPS":                      0,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 1,
			"Authorization":            0,
			"Advice":                   0,
		},
	}

	table29 := Table{
		Name: "272",
		ConditionsValues: map[string]int{
			"ATM":                      1,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     1,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      0,
			"CPS":                      1,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 1,
			"Authorization":            0,
			"Advice":                   0,
		},
	}

	table30 := Table{
		Name: "273",
		ConditionsValues: map[string]int{
			"ATM":                      2,
			"CardnNotPresent":          2,
			"CardPresent":              2,
			"VSDC":                     1,
			"NotVSDC":                  2,
			"TandE":                    2,
			"CPS":                      2,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           2,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         1,
			"IncrementalAuthorization": 2,
			"Reversal":                 1,
			"Authorization":            0,
			"Advice":                   0,
		},
	}

	table31 := Table{
		Name: "231",
		ConditionsValues: map[string]int{
			"ATM":                      0,
			"CardnNotPresent":          0,
			"CardPresent":              1,
			"VSDC":                     2,
			"NotVSDC":                  2,
			"TandE":                    2,
			"POS":                      1,
			"CPS":                      2,
			"AccountVerification":      2,
			"CreditVoucher":            2,
			"BalanceInquiry":           1,
			"CardAccountTransfer":      2,
			"isDeferredAuthorization":  2,
			"WithPIN":                  2,
			"PINChangeUnblock":         2,
			"IncrementalAuthorization": 2,
			"Reversal":                 0,
			"Authorization":            1,
			"Advice":                   0,
		},
	}

	return []Table{table1, table2, table3, table4, table5, table6, table7, table8, table9, table10, table11, table12, table13, table14, table15, table16, table17, table18, table19, table20, table21, table22, table23, table24, table25, table26, table27, table28, table29, table30, table31}
}
